-- Supabase 대시보드 > SQL Editor에서 한 번 실행하세요.
create table if not exists public.tshirt_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  size text not null check (size in ('S', 'M', 'L', 'XL', '2XL')),
  photo_path text not null,
  created_at timestamptz not null default now()
);

alter table public.tshirt_submissions enable row level security;

create policy "Anyone can submit tshirt details"
on public.tshirt_submissions for insert
to anon
with check (true);

-- 비공개 사진 버킷 생성
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'tshirt-photos',
  'tshirt-photos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Anyone can upload a tshirt photo"
on storage.objects for insert
to anon
with check (bucket_id = 'tshirt-photos');

-- 익명 사용자는 제출 명단이나 사진을 읽고 지울 수 없습니다.
-- 관리자는 Supabase 대시보드의 Table Editor / Storage에서 확인하고 다운로드합니다.
